version: '3'

silent: true

tasks:
  install:
    cmds:
      - cmd: pip install --upgrade pip
      - cmd: pip install virtualenv
      - cmd: test -d .venv || virtualenv .venv
      - cmd: .venv/bin/pip install --upgrade -r requirements.txt
        platforms: [ darwin, linux ]
      - cmd: .venv\Scripts\pip install --upgrade -r requirements.txt
        platforms: [ windows ]

  test:
    cmds:
      - .venv/bin/python test_arangodb_document_store.py